title: Rachel Basile # your name (or website title) here
logo: "/images/Screen Shot 2023-03-22 at 12.11.38 PM.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst & Educator <br><br>
  Lover of Podcasts  <br><br>
  <a href="https://www.linkedin.com/in/rachel-basile/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
